name: simple

on: 
    workflow_dispatch:
jobs:
    build: 
        runs-on: [self-hosted, linux, x64]
        steps: 
            - uses: actions/checkout@v2
            - name: Run a one-line script
              run: echo "Hello, World!"
                 sleep 15
                 echo "Goodbye, World!"