name: simple

on: 
    push:
        branches:
            - main
jobs:
    build: 
        runs-on: [self-hosted, linux, x64]
        steps: 
            - uses: actions/checkout@v3
            - name: Run a one-line script
              run: echo "Hello, World!"
                 sleep 15
                 echo "Goodbye, World!"